#!/usr/bin/env bash
# Generate .env for self-host (free profile, local images). Writes credentials.generated.txt (600).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

FORCE=0
for arg in "$@"; do
  if [[ "$arg" == "--force" ]]; then
    FORCE=1
  fi
done

if [[ -f "$ROOT/.env" && "$FORCE" -ne 1 ]]; then
  echo ".env already exists. Refusing to overwrite (would desync Postgres volume)." >&2
  echo "Use: $0 --force only after ./scripts/03-stack-down.sh --remove-volumes" >&2
  exit 1
fi

if ! command -v openssl >/dev/null 2>&1; then
  echo "openssl is required." >&2
  exit 1
fi

POSTGRES_VOLUME_NAME="${POSTGRES_VOLUME_NAME:-colcoor_selfhost_postgres_data}"
if [[ "${COLCOOR_ALLOW_NEW_SECRETS_WITH_EXISTING_VOLUME:-}" != "1" ]]; then
  if command -v docker >/dev/null 2>&1 && docker volume inspect "$POSTGRES_VOLUME_NAME" >/dev/null 2>&1; then
    echo "Docker volume ${POSTGRES_VOLUME_NAME} exists. Regenerating secrets will break DB auth." >&2
    echo "Run: ./scripts/03-stack-down.sh --remove-volumes  then re-run this script." >&2
    exit 1
  fi
fi

POSTGRES_DB="${POSTGRES_DB:-colcoor}"
POSTGRES_USER="${POSTGRES_USER:-colcoor}"
POSTGRES_PASSWORD="$(openssl rand -hex 32)"
JWT_SECRET="$(openssl rand -hex 48)"

DATABASE_URL="postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@pgbouncer:6432/${POSTGRES_DB}"
DATABASE_MIGRATION_URL="postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"

CRED="$ROOT/credentials.generated.txt"
ENV_OUT="$ROOT/.env.tmp"

umask 077
cat >"$ENV_OUT" <<EOF
# Generated by Colcoor self-host bundle (01-setup-env.sh). Do not commit.
NODE_ENV=production
COLCOOR_ENV=production
PORT=8000
WEB_CONCURRENCY=2
COLCOOR_LOG_LEVEL=INFO

COLCOOR_DEPLOYMENT_PROFILE=free
COLCOOR_LICENSE_TYPE=free

COLCOOR_IMAGE_STORAGE=local
COLCOOR_LOCAL_IMAGE_STORAGE_PATH=/var/lib/colcoor/images

SELF_HOST_HTTP_PORT=8080
CORS_ORIGINS=
DOMAIN=

POSTGRES_DB=${POSTGRES_DB}
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

DATABASE_URL=${DATABASE_URL}
DATABASE_MIGRATION_URL=${DATABASE_MIGRATION_URL}

REDIS_URL=redis://redis:6379/0
JWT_SECRET=${JWT_SECRET}

COLCOOR_EVENT_PURGE_SCHEDULER_ENABLED=true
RATE_LIMIT_TRUST_PROXY=true
EOF

mv "$ENV_OUT" "$ROOT/.env"

cat >"$CRED" <<EOF
# Colcoor self-host credentials ($(date -u +%Y-%m-%dT%H:%M:%SZ))
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_DB=${POSTGRES_DB}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
JWT_SECRET=${JWT_SECRET}
DATABASE_URL=${DATABASE_URL}
DATABASE_MIGRATION_URL=${DATABASE_MIGRATION_URL}
EOF
chmod 600 "$CRED" "$ROOT/.env"

echo "Wrote $ROOT/.env and $CRED (mode 600)."
echo "Next: ./scripts/02-stack-up.sh"
