#!/usr/bin/env bash
# Generate .env with random POSTGRES_PASSWORD and JWT_SECRET, plus DATABASE_URL.
# Writes credentials.generated.txt (mode 600) for secure archival; remove after copying elsewhere.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

FORCE=0
for arg in "$@"; do
  if [[ "$arg" == "--force" ]]; then
    FORCE=1
  fi
done

if [[ -f "$ROOT/.env" && "$FORCE" -ne 1 ]]; then
  echo ".env already exists. Refusing to overwrite (would desync secrets from existing Postgres data)." >&2
  echo "Use: $0 --force   only after fresh install or after stack-down --remove-volumes." >&2
  exit 1
fi

if ! command -v openssl >/dev/null 2>&1; then
  echo "openssl is required." >&2
  exit 1
fi

# Postgres only applies POSTGRES_PASSWORD on first init of the data volume. If the Docker
# volume colcoor_postgres_data already exists, new random passwords in .env will NOT match
# the database (backend: "password authentication failed for user colcoor").
POSTGRES_VOLUME_NAME="${POSTGRES_VOLUME_NAME:-colcoor_postgres_data}"
will_write_new_secrets=0
if [[ ! -f "$ROOT/.env" ]] || [[ "$FORCE" -eq 1 ]]; then
  will_write_new_secrets=1
fi
if [[ "$will_write_new_secrets" -eq 1 ]] && [[ "${COLCOOR_ALLOW_NEW_SECRETS_WITH_EXISTING_VOLUME:-}" != "1" ]]; then
  if command -v docker >/dev/null 2>&1 && docker volume inspect "$POSTGRES_VOLUME_NAME" >/dev/null 2>&1; then
    cat >&2 <<EOF
Refusing to write new Postgres secrets: Docker volume '${POSTGRES_VOLUME_NAME}' already exists.

The password inside that volume was set on first Postgres start and does not change when you
regenerate .env. Fix one of these ways:

  A) Fresh database (destroys Colcoor data in that volume):
       ./scripts/03-stack-down.sh --remove-volumes
       Then re-run: $0 $([[ "$FORCE" -eq 1 ]] && echo --force)

  B) Keep existing data: restore the original .env (same POSTGRES_PASSWORD as when the volume
     was created), or change the Postgres role password to match your new DATABASE_URL (advanced).

Only if you know what you are doing:
  COLCOOR_ALLOW_NEW_SECRETS_WITH_EXISTING_VOLUME=1 $0 ...
EOF
    exit 1
  fi
fi

POSTGRES_DB="${POSTGRES_DB:-colcoor}"
POSTGRES_USER="${POSTGRES_USER:-colcoor}"
POSTGRES_PASSWORD="$(openssl rand -hex 32)"
JWT_SECRET="$(openssl rand -hex 48)"

# Password is hex-only; safe inside URLs without extra encoding.
DATABASE_URL="postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@pgbouncer:6432/${POSTGRES_DB}"
DATABASE_MIGRATION_URL="postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"

CRED="$ROOT/credentials.generated.txt"
ENV_OUT="$ROOT/.env.tmp"

umask 077
cat >"$ENV_OUT" <<EOF
# Generated by Colcoor enterprise bundle (01-setup-env.sh). Do not commit.
NODE_ENV=production
COLCOOR_ENV=production
PORT=8000
WEB_CONCURRENCY=${WEB_CONCURRENCY:-2}
COLCOOR_LOG_LEVEL=${COLCOOR_LOG_LEVEL:-INFO}
CORS_ORIGINS=${CORS_ORIGINS:-}
DOMAIN=

POSTGRES_DB=${POSTGRES_DB}
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

DATABASE_URL=${DATABASE_URL}
DATABASE_MIGRATION_URL=${DATABASE_MIGRATION_URL}

JWT_SECRET=${JWT_SECRET}

COLCOOR_EVENT_PURGE_SCHEDULER_ENABLED=${COLCOOR_EVENT_PURGE_SCHEDULER_ENABLED:-true}
EOF

mv "$ENV_OUT" "$ROOT/.env"

cat >"$CRED" <<EOF
# Colcoor generated credentials ($(date -u +%Y-%m-%dT%H:%M:%SZ))
# Permissions should be 600. Store in a vault and delete this file from the server if required.

POSTGRES_USER=${POSTGRES_USER}
POSTGRES_DB=${POSTGRES_DB}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

JWT_SECRET=${JWT_SECRET}

DATABASE_URL=${DATABASE_URL}
DATABASE_MIGRATION_URL=${DATABASE_MIGRATION_URL}
EOF
chmod 600 "$CRED" "$ROOT/.env"

echo "Wrote $ROOT/.env and $CRED (mode 600)."
echo ""
echo "DATABASE_URL (also in .env and credentials file):"
echo "  ${DATABASE_URL}"
echo ""
echo "Next: ./scripts/02-stack-up.sh"
