#!/usr/bin/env bash
# Orchestrate GCP provisioning for Colcoor multi-VM (Cloud SQL, Redis, GCS, pool sizing).
#
# Usage:
#   ./scripts/gcp/provision-infra.sh --config scripts/gcp/gcp.env --shared-env ./shared.env
#   ./scripts/gcp/provision-infra.sh --config scripts/gcp/gcp.env --shared-env ./shared.env --with-lb
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=lib/common.sh
source "${SCRIPT_DIR}/lib/common.sh"

CONFIG=""
SHARED_ENV=""
WITH_LB=0
SKIP_APIS=0
DRY_RUN=0

usage() {
  cat <<'EOF'
Usage: provision-infra.sh --config gcp.env --shared-env PATH [options]

Options:
  --with-lb          Also run provision-load-balancer.sh (VMs must exist)
  --skip-apis        Do not enable GCP APIs (default: enable sqladmin, redis, compute, storage)
  --dry-run          Pass through to child scripts

Creates/updates shared.env with Postgres, Redis, GCS, JWT, production flags, pool sizing.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --config=*)
      CONFIG="${1#*=}"
      shift
      ;;
    --config)
      CONFIG="${2:-}"
      shift 2
      ;;
    --shared-env=*)
      SHARED_ENV="${1#*=}"
      shift
      ;;
    --shared-env)
      SHARED_ENV="${2:-}"
      shift 2
      ;;
    --with-lb)
      WITH_LB=1
      shift
      ;;
    --skip-apis)
      SKIP_APIS=1
      shift
      ;;
    --dry-run)
      DRY_RUN=1
      shift
      ;;
    -h | --help)
      usage
      exit 0
      ;;
    *)
      gcp_die "unknown argument: $1"
      ;;
  esac
done

[[ -n "$SHARED_ENV" ]] || gcp_die "--shared-env is required"
gcp_load_config "$CONFIG"
gcp_require_gcloud

SHARED_ABS="$SHARED_ENV"
[[ "$SHARED_ABS" == /* ]] || SHARED_ABS="$(pwd)/$SHARED_ENV"

if [[ ! -f "$SHARED_ABS" ]]; then
  umask 077
  cat >"$SHARED_ABS" <<EOF
# Colcoor shared.env — generated by provision-infra.sh
# $(date -u +%Y-%m-%dT%H:%M:%SZ)
EOF
  chmod 600 "$SHARED_ABS"
fi

DRY_FLAG=()
[[ "$DRY_RUN" == "1" ]] && DRY_FLAG=(--dry-run)

gcp_run gcloud config set project "$COLCOOR_GCP_PROJECT" >/dev/null

if [[ "$SKIP_APIS" != "1" && "$DRY_RUN" != "1" ]]; then
  echo "Enabling GCP APIs..."
  gcp_run gcloud services enable \
    sqladmin.googleapis.com \
    redis.googleapis.com \
    compute.googleapis.com \
    storage.googleapis.com \
    servicenetworking.googleapis.com \
    --project="$COLCOOR_GCP_PROJECT"
fi

# App / license defaults for hosted production.
gcp_env_set_if_missing "$SHARED_ABS" "COLCOOR_ENV" "production"
gcp_env_set_if_missing "$SHARED_ABS" "NODE_ENV" "production"
gcp_env_set_if_missing "$SHARED_ABS" "COLCOOR_DEPLOYMENT_PROFILE" "gcp-production"
gcp_env_set_if_missing "$SHARED_ABS" "RATE_LIMIT_TRUST_PROXY" "true"
gcp_env_set_if_missing "$SHARED_ABS" "COLCOOR_EVENT_PURGE_SCHEDULER_ENABLED" "true"

if [[ -f "$SHARED_ABS" ]]; then
  # shellcheck disable=SC1090
  set -a
  source "$SHARED_ABS"
  set +a
fi
if [[ -z "${JWT_SECRET:-}" ]]; then
  JWT_SECRET="$(gcp_random_hex 48)"
  gcp_env_set "$SHARED_ABS" "JWT_SECRET" "$JWT_SECRET"
  echo "Generated JWT_SECRET"
fi

"${SCRIPT_DIR}/provision-cloudsql.sh" --config "$CONFIG" --shared-env "$SHARED_ABS" "${DRY_FLAG[@]}"
"${SCRIPT_DIR}/provision-redis.sh" --config "$CONFIG" --shared-env "$SHARED_ABS" "${DRY_FLAG[@]}"
"${SCRIPT_DIR}/provision-gcs.sh" --config "$CONFIG" --shared-env "$SHARED_ABS" "${DRY_FLAG[@]}"
"${SCRIPT_DIR}/size-db-pools.sh" --shared-env "$SHARED_ABS" "${DRY_FLAG[@]}"

if [[ "$WITH_LB" == "1" ]]; then
  "${SCRIPT_DIR}/provision-load-balancer.sh" --config "$CONFIG" "${DRY_FLAG[@]}"
fi

echo ""
echo "GCP infra provisioning complete."
echo "  shared.env: ${SHARED_ABS}"
echo "Next:"
echo "  ./scripts/deploy-multi-vm.sh write-env --role=primary --shared-env ${SHARED_ABS}"
echo "  ./scripts/deploy-multi-vm.sh deploy-primary --shared-env ${SHARED_ABS}"
